from __future__ import annotations


class DiscoveryConstants:
    ORDINAL_INDEX = {
        "first": 0,
        "one": 0,
        "1": 0,
        "number one": 0,
        "second": 1,
        "two": 1,
        "2": 1,
        "number two": 1,
        "third": 2,
        "three": 2,
        "3": 2,
        "number three": 2,
        "fourth": 3,
        "four": 3,
        "4": 3,
        "number four": 3,
        "fifth": 4,
        "five": 4,
        "5": 4,
        "number five": 4,
        "sixth": 5,
        "six": 5,
        "6": 5,
        "number six": 5,
    }
    TRENDING_HINTS = frozenset(
        {
            "what's trending",
            "whats trending",
            "what is trending",
            "what's popular",
            "what is popular",
            "what's hot",
            "what is hot",
            "trending",
            "popular",
            "what are people listening to",
            "what is everyone listening to",
            "top content",
            "show me trending",
            "show me what's trending",
            "read me the trending list",
            "what's trending right now",
            "what's on trend",
            "trending audio",
            "popular picks",
            "most popular right now",
        }
    )
    LOCAL_HINTS = frozenset(
        {
            "local",
            "nearby",
            "near me",
            "near here",
            "local content",
            "what's local",
            "whats local",
            "what is local",
            "local community",
            "my local community",
            "from my local community",
            "something from my local community",
            "community",
            "around me",
            "around here",
            "content near me",
            "local recordings",
            "nearby recordings",
            "local audio",
            "nearby audio",
            "what's happening near me",
            "my city",
            "my town",
            "from my city",
            "from my town",
            "my community",
            "from my community",
            "something from my community",
            "play community",
            "play community content",
            "what's happening locally",
            "whats happening locally",
            "locally",
        }
    )
    BROWSE_HINTS = frozenset(
        {
            "what's on",
            "whats on",
            "what's available",
            "whats available",
            "what have you got",
            "what's new",
            "whats new",
            "any new content",
            "what's been published",
            "what do you recommend",
            "recommend something",
            "any new episodes",
            "what's fresh",
            "whats fresh",
            "what dropped today",
            "let me hear what's new",
            "show me what you've got",
            "browse",
        }
    )
    FEEDBACK_SKIP_HINTS = frozenset(
        {
            "skip",
            "never mind",
            "no thanks",
            "ignore that",
            "skip feedback",
            "move on",
            "don't bother",
            "i don't want to rate",
            "no comment",
            "pass",
            "skip the rating",
            "carry on",
            "i'd rather not say",
            "just play the next one",
            "whatever",
            "doesn't matter",
            "skip it",
            "not bothered",
            "can't be bothered",
        }
    )
    ALEXA_TO_NLP = {
        "PlayContentIntent": "general",
        "PlayLatestContentIntent": "general",
        "PlayByCreatorIntent": "creator",
        "PlayByOrganizationIntent": "organization",
        "PlayPublicationIntent": "publication",
        "WhatsTrendingIntent": "trending",
        "PlayRecommendationIntent": "trending",
        "PlayLocalIntent": "local",
        "BrowseContentIntent": "browse",
        "ShowMoreBrowseIntent": "show_more",
        "SetLocationIntent": "location_set",
        "TownCaptureIntent": "town_capture",
        "ClarifySelectionIntent": "general",
        "AMAZON.FallbackIntent": "general",
    }
    RESERVED_DISCOVERY_PHRASES = frozenset(
        {
            "",
            "anything",
            "anything to listen to",
            "audio",
            "content",
            "give me anything",
            "give me something",
            "give me something new",
            "give me something to listen to",
            "find",
            "find me",
            "find something",
            "hear something",
            "let me listen",
            "listen",
            "play",
            "play anything",
            "play audio",
            "play content",
            "play for me",
            "play me anything",
            "play me something",
            "play recording",
            "play recordings",
            "play something",
            "put something on",
            "read me something",
            "recording",
            "recordings",
            "search",
            "search for something",
            "search something",
            "something",
            "something to listen to",
            "start",
            "start listening",
            "start playing",
            "start something",
            "whatever",
        }
    )
    PUBLICATION_SOURCE_PLACEHOLDERS = frozenset(
        {
            "publication",
            "publications",
            "a publication",
            "the publication",
            "play publication",
            "play publications",
            "play a publication",
            "play the publication",
            "play something from a publication",
            "find publication",
            "find a publication",
            "latest publication",
            "the latest publication",
            "something from a publication",
        }
    )
    CREATOR_SOURCE_PLACEHOLDERS = frozenset(
        {
            "creator",
            "a creator",
            "the creator",
            "from a creator",
            "play creator",
            "play a creator",
            "play from a creator",
            "play something from a creator",
            "play me something from a creator",
        }
    )
    ORGANIZATION_SOURCE_PLACEHOLDERS = frozenset(
        {
            "talking newspaper",
            "talking news paper",
            "a talking newspaper",
            "a talking news paper",
            "the talking newspaper",
            "the talking news paper",
            "from a talking newspaper",
            "from a talking news paper",
            "play from a talking newspaper",
            "play from a talking news paper",
            "play something from a talking newspaper",
            "play something from a talking news paper",
            "play me a talking newspaper",
            "play me a talking news paper",
        }
    )
    GENERIC_ORGANIZATION_WORDS = frozenset(
        {
            "a",
            "an",
            "the",
            "play",
            "from",
            "something",
            "me",
            "content",
            "recording",
            "recordings",
            "by",
            "for",
            "talking",
            "news",
            "newspaper",
            "paper",
            "organisation",
            "organization",
        }
    )
