class EventConstants:
    CONTENT = "content"
    PUBLICATION = "publication"
    FEEDBACK_GIVEN = "feedback.given"
    FOLLOWED_CREATOR = "user.followed_creator"
    FOLLOWED_ORGANIZATION = "user.followed_organization"
    UNFOLLOWED_CREATOR = "user.unfollowed_creator"
    UNFOLLOWED_ORGANIZATION = "user.unfollowed_organization"
    REPORTED_CONTENT = "user.reported_content"
    REPORTED_CREATOR = "user.reported_creator"
    PLAYBACK_PREFIX = "playback."
