from __future__ import annotations


class OrganizationConstants:
    SOURCE_PLACEHOLDERS = frozenset(
        {
            "talking newspaper",
            "talking newspapers",
            "talking news paper",
            "talking news papers",
            "talking news",
            "talking paper",
            "talking papers",
            "audio newspaper",
            "audio newspapers",
            "audio news paper",
            "audio news papers",
            "audio news",
            "audio paper",
            "audio papers",
            "spoken newspaper",
            "spoken newspapers",
            "spoken news",
            "local talking newspaper",
            "local talking newspapers",
            "a talking newspaper",
            "a talking news paper",
            "the talking newspaper",
            "the talking news paper",
            "from a talking newspaper",
            "from a talking news paper",
            "play from a talking newspaper",
            "play from a talking news paper",
            "play something from a talking newspaper",
            "play something from a talking news paper",
            "play me a talking newspaper",
            "play me a talking news paper",
        }
    )
    ASR_REPAIR_PHRASES = frozenset(
        {
            "top english paper",
            "top english newspaper",
            "talk english paper",
            "talk english newspaper",
        }
    )
    GENERIC_WORDS = frozenset(
        {
            "a",
            "an",
            "any",
            "audio",
            "available",
            "by",
            "can",
            "choose",
            "content",
            "could",
            "d",
            "different",
            "find",
            "for",
            "from",
            "get",
            "give",
            "have",
            "hear",
            "i",
            "id",
            "latest",
            "let",
            "like",
            "listen",
            "local",
            "me",
            "new",
            "news",
            "newspaper",
            "newspapers",
            "of",
            "on",
            "one",
            "organisation",
            "organisations",
            "organization",
            "organizations",
            "other",
            "paper",
            "papers",
            "play",
            "please",
            "put",
            "random",
            "recommend",
            "recording",
            "recordings",
            "select",
            "service",
            "services",
            "show",
            "some",
            "something",
            "source",
            "sources",
            "spoken",
            "talking",
            "the",
            "to",
            "want",
            "would",
            "you",
        }
    )
